# Generated by Django 3.0 on 2022-01-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model

def copy_data(apps, schema_editor):
    Profile = apps.get_model('oc_lettings_site', 'Profile')
    appProfiles = apps.get_model('profiles', 'Profile')
    appUser = get_user_model()

    for profiles in Profile.objects.all():
        new_profiles = appProfiles()
        user_profile = appUser.objects.filter(id=profiles.user.id).first()
        new_profiles.favorite_city = '%s' % (profiles.favorite_city)
        new_profiles.user_id = user_profile.id
        new_profiles.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_city', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(copy_data),
    ]
