# Generated by Django 3.0 on 2022-01-12 15:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def copy_data(apps, schema_editor):
    Address = apps.get_model('oc_lettings_site', 'Address')
    appAddress = apps.get_model('lettings', 'Address')

    Letting = apps.get_model('oc_lettings_site', 'Letting')
    appLetting = apps.get_model('lettings', 'Letting')

    for address in Address.objects.all():
        new_address = appAddress()
        new_address.number = '%s' % (address.number)
        new_address.street = '%s' % (address.street)
        new_address.city = '%s' % (address.city)
        new_address.state = '%s' % (address.state)
        new_address.zip_code = '%s' % (address.zip_code)
        new_address.country_iso_code = '%s' % (address.country_iso_code)
        new_address.save()

    for letting in Letting.objects.all():
        new_letting = appLetting()
        address = appAddress.objects.filter(id=letting.address.id).first()
        new_letting.title = '%s' % (letting.title)
        new_letting.address = address
        new_letting.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('zip_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('country_iso_code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Letting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lettings.Address')),
            ],
        ),
        migrations.RunPython(copy_data),
    ]
